services:
  - type: web
    name: barbearia-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn barbearia.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: barbearia.settings
      - key: PYTHON_VERSION
        value: 3.11
